<?php

$token = $this->config['hashed'];
$username = $this->username;
$reset_link = $this->serverUrl() . $this->url('user-reset-password', array(), array('query' => array(
        'username' => $username,
        'token' => $token
    )));

?>

<div>
    <p>Hello <b><?php echo $username ?></b></p>
    <p>A password request has been issued on your account.</p>
    <p>Please click <a href="<?php echo $reset_link ?>">here</a> to reset your password</p>
</div>